//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVEUCILISNA_KNJIZNICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrojDokumenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BrojDokumenta()
        {
            this.Transakcijas = new HashSet<Transakcija>();
        }
    
        public int BrojDokumentaID { get; set; }
        public string NazivDokumenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcija> Transakcijas { get; set; }
    }
}
