//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVEUCILISNA_KNJIZNICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linija
    {
        public int LinijaID { get; set; }
        public int TransakcijaID { get; set; }
        public int KnjigaID { get; set; }
    
        public virtual Knjiga Knjiga { get; set; }
        public virtual Transakcija Transakcija { get; set; }
    }
}
