//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVEUCILISNA_KNJIZNICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transakcija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transakcija()
        {
            this.Linijas = new HashSet<Linija>();
        }
    
        public int TransakcijaID { get; set; }
        public int BrojDokumentaID { get; set; }
        public System.DateTime DatumTransakcije { get; set; }
        public int KorisnikID { get; set; }
    
        public virtual BrojDokumenta BrojDokumenta { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linija> Linijas { get; set; }
    }
}
